# Generated by Django 3.1.3 on 2020-11-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reference_code',
            new_name='code',
        ),
    ]
